#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_ANDROID_TIMED_OUTPUT)	+= timed_output.o
obj-$(CONFIG_ISA1000)		+= isa1000.o
obj-$(CONFIG_SEC_VIB)		+= sec_vib.o
obj-$(CONFIG_STEP_MOTOR_STSPIN220)        += stspin220_step_motor.o
