obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o sec_battery_sysfs.o sec_battery_dt.o
obj-$(CONFIG_OF)		+= sec_adc.o
obj-$(CONFIG_BATTERY_CISD)	+= sec_cisd.o
obj-$(CONFIG_MULTI_CHARGING)	+= sec_multi_charger.o
obj-$(CONFIG_STEP_CHARGING)	+= sec_step_charging.o
obj-$(CONFIG_UPDATE_BATTERY_DATA)	+= sec_battery_data.o
obj-$(CONFIG_BATTERY_NOTIFIER)	+= battery_notifier.o
obj-$(CONFIG_CCIC_NOTIFIER)		+= sec_pd.o

obj-$(CONFIG_FUELGAUGE_SM5713)		+= sm5713_fuelgauge.o

obj-$(CONFIG_CHARGER_SM5713)	+= sm5713_charger.o sm5713_charger_oper.o
