obj-$(CONFIG_TYPEC)		+= typec.o
obj-$(CONFIG_TYPEC_WCOVE)	+= typec_wcove.o
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi/

obj-$(CONFIG_CCIC_SM5713)	+= sm5713/
obj-y		+= sep/
obj-$(CONFIG_USB_TYPEC_MANAGER_NOTIFIER)	+= manager/