obj-$(CONFIG_SCHED_EMS) += ems.o

ems-y += main.o
ems-y += core.o
ems-y += prefer.o
ems-y += energy_table.o
ems-y += multi_load.o
ems-y += lbt.o
ems-y += ontime.o
ems-y += sysbusy.o
ems-y += profile.o
ems-$(CONFIG_CPU_FREQ_GOV_ENERGY_ADAPTIVE) += aigo.o
ems-y += taskboost.o
ems-y += gpuboost.o
