obj-$(CONFIG_SCHED_EMS) += ems.o

ems-y += core.o
ems-y += prefer.o
ems-y += cpu_select.o
ems-y += energy_table.o
ems-y += lbt.o
ems-y += init_util.o
ems-y += ontime.o
ems-y += freqvar_tune.o
ems-y += taskboost.o
