#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_ICM42605M) += gyro_icm42605m.o
obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_LSM6DSL)	+= gyro_lsm6dsl.o
obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_K6DS3TR)	+= gyro_k6ds3tr.o