# Makefile of gnss_if

# obj-$(CONFIG_GNSS_SHMEM_IF) += gnss_main.o gnss_io_device.o gnss_link_device_shmem.o \
#						gnss_keplerctl_device.o gnss_utils.o

obj-$(CONFIG_GNSS_SHMEM_IF) += gnss_main.o gnss_io_device.o \
						gnss_keplerctl_device.o \
						gnss_link_device_shmem.o \
						gnss_link_device_memory.o \
						pmu-gnss.o \
						gnss_utils.o
