#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SSP_MAGNETIC_AK09918C) 	+= magnetic_ak09918c.o
obj-$(CONFIG_SENSORS_SSP_MAGNETIC_AK09916C) 	+= magnetic_ak09916c.o
obj-$(CONFIG_SENSORS_SSP_MAGNETIC_LSM303AH)	+= magnetic_lsm303ah.o
obj-$(CONFIG_SENSORS_SSP_MAGNETIC_MMC5603)	+= magnetic_mmc5603.o