# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_EXYNOS_GRAPHICS_G2D) := g2d.o
g2d-objs := g2d_drv.o g2d_task.o g2d_regs.o
g2d-objs += g2d_uapi_process.o g2d_command.o
g2d-objs += g2d_fence.o g2d_perf.o