name: Upstream Kernel to 5.4

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  upstream-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Fetch Upstream Kernel
      run: |
        git remote add upstream https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        git fetch upstream

    - name: Rebase to Kernel 5.4
      run: |
        git checkout -b kernel-5.4-upstreaming
        git rebase upstream/linux-5.4.y
      continue-on-error: true

    - name: Push Changes to New Branch
      run: |
        git push origin kernel-5.4-upstreaming
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Automated Upstream to Kernel 5.4"
        pr_body: "This is an automated pull request to upstream the kernel to version 5.4"
        destination_branch: "main" # Change this to your repo's default branch if it's not 'main'
        source_branch: "kernel-5.4-upstreaming"
