name: Development Build (Galaxy A50)

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'

jobs:
  oneui-s:
    name: Build One UI 4
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --magisk --automated --device a50 --variant oneui --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: One UI Four Kernel ZIPs
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload kernel image artifact
      uses: actions/upload-artifact@v2
      with:
        name: One UI Four Kernel Image
        path: 'tools/make/boot.img'
        if-no-files-found: error

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: One UI Four Kernel Configs
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

  oneui-s-p:
    name: Build One UI 4 (Permissive)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --magisk --automated --device a50 --variant oneui --android 12 --permissive

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: One UI Four Kernel ZIPs
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload kernel image artifact
      uses: actions/upload-artifact@v2
      with:
        name: One UI Four Permissive Kernel Image
        path: 'tools/make/boot.img'
        if-no-files-found: error

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: One UI Four Kernel Configs
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error
