name: Upstream Kernel to 5.4

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  upstream-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Fetch Upstream Kernel
      run: |
        git remote add upstream https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        git fetch upstream

    - name: Rebase to Kernel 5.4
      run: |
        git checkout -b kernel-5.4-upstreaming
        git rebase upstream/linux-5.4.y
      continue-on-error: true

    - name: Zip Upstreamed Source
      run: |
        git archive --format=zip --output=kernel-5.4-upstream.zip HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Upstreamed Source as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel-5.4-Upstreamed-Source
        path: kernel-5.4-upstream.zip

    # Remove the following steps as they are no longer needed
    # - name: Push Changes to New Branch
    #   ...
    # - name: Create Pull Request
    #   ...
