name: Build FreshCore (Staging)

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  a50:
    name: Build Galaxy A50
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install build-essential libelf-dev kernel-package bzip2 lib32stdc++6 libc6-dev-i386 git -y
      
    - name: Install Toolchain
      run: |
          set -eo pipefail
          export ORIG_DIR=$(pwd)
          git clone -n https://github.com/arter97/arm64-gcc.git ${HOME}/toolchain
          cd ${HOME}/toolchain
          git checkout cd9eb72bace3b4d682d5251a9eb4829bdd0ec2ca
          cd $ORIG_DIR
        
    - name: Build FreshCore Kernel
      run: |
          set -eo pipefail
          echo "  I: Building FreshCore CI $GITHUB_RUN_NUMBER"
          export KBUILD_BUILD_VERSION=$GITHUB_RUN_NUMBER
          ./build.sh a50 ci
          
    - name: Prepare Release
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname FRSH_CORE_*.zip` ./release/
          cp .config ./release/kernel_config_a50.txt

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50 Kernel Image (staging-${{ github.run_number }})
        path: 'tools/package/boot.img'
        if-no-files-found: error

    - name: Upload config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50 Kernel Config (staging-${{ github.run_number }})
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a50_release_staging-${{ github.run_number }})
        path: 'release'
        if-no-files-found: error

  a50_recovery:
    name: Build Galaxy A50 Recovery Image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install build-essential libelf-dev kernel-package bzip2 lib32stdc++6 libc6-dev-i386 git -y
      
    - name: Install Toolchain
      run: |
          set -eo pipefail
          export ORIG_DIR=$(pwd)
          git clone -n https://github.com/arter97/arm64-gcc.git ${HOME}/toolchain
          cd ${HOME}/toolchain
          git checkout cd9eb72bace3b4d682d5251a9eb4829bdd0ec2ca
          cd $ORIG_DIR
        
    - name: Build FreshCore Kernel
      run: |
          set -eo pipefail
          echo "  I: Building FreshCore CI $GITHUB_RUN_NUMBER"
          export KBUILD_BUILD_VERSION=$GITHUB_RUN_NUMBER
          ./build-recovery.sh a50 ci
          mv -f ./tools/aik/a50/split_img/boot.img-zImage ./Image
          cp .config ./kernel_config_a50_recovery.txt

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50 Recovery Kernel Image (staging-${{ github.run_number }})
        path: 'Image'
        if-no-files-found: error

    - name: Upload config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50 Kernel Config (staging-${{ github.run_number }})
        path: 'kernel_config_a50_recovery.txt'
        if-no-files-found: error

  a50s:
    name: Build Galaxy A50s
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install build-essential libelf-dev kernel-package bzip2 lib32stdc++6 libc6-dev-i386 git -y
      
    - name: Install Toolchain
      run: |
          set -eo pipefail
          export ORIG_DIR=$(pwd)
          git clone -n https://github.com/arter97/arm64-gcc.git ${HOME}/toolchain
          cd ${HOME}/toolchain
          git checkout cd9eb72bace3b4d682d5251a9eb4829bdd0ec2ca
          cd $ORIG_DIR
        
    - name: Build FreshCore Kernel
      run: |
          set -eo pipefail
          echo "  I: Building FreshCore CI $GITHUB_RUN_NUMBER"
          export KBUILD_BUILD_VERSION=$GITHUB_RUN_NUMBER
          ./build.sh a50s ci
          
    - name: Prepare Release
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname FRSH_CORE_*.zip` ./release/
          cp .config ./release/kernel_config_a50s.txt

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50s Kernel Image (staging-${{ github.run_number }})
        path: 'tools/package/boot.img'
        if-no-files-found: error

    - name: Upload config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50s Kernel Config (staging-${{ github.run_number }})
        path: 'release/kernel_config_a50s.txt'
        if-no-files-found: error

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a50s_release_staging-${{ github.run_number }})
        path: 'release'
        if-no-files-found: error

  release:
    name: Release files and configs
    if: always()
    needs: [a50, a50s]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - uses: JantHsueh/get-git-log-action@1.0
      id: log
      
    - name: Merge Galaxy A50 release
      uses: actions/download-artifact@v2
      with:
        name: a50_release_staging-${{ github.run_number }})
        path: release
      
    - name: Merge Galaxy A50s release
      uses: actions/download-artifact@v2
      with:
        name: a50s_release_staging-${{ github.run_number }})
        path: release
        
    - name: Upload release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag
        tag_name: ci_${{ github.run_number }}-staging
        release_name: ci_staging-${{ github.run_number }}
        body: ${{ steps.log.outputs.log }}
        asset_files: './release'

